### ISSUE TITLE
problem: fix sqlite whitelist logic days vs reporttime

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/verbose-robot#17]
https://github.com/csirtgadgets/bearded-avenger/issues/408

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/pull/409

**Comment by deanpemberton** [comment]
I haven't tested against this but my feeling is that it might not be as much of a problem.

The code does a...
~~~python
if not filters.get('reported_at') and not filters.get('days') and not filters.get('hours'):
        if not filters.get('itype'):
            filters['days'] = str(DAYS_SHORT)
        else:
            filters['days'] = str(FEED_DAYS[filters['itype']])
~~~

So it checks if `reported_at` exists before setting default values for `days`.  

It probably needs a check, but the priority is low I'd say.
