### ISSUE TITLE
problem: hunters missing confidence factor

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/verbose-robot#73]
see gist: e506dd

**Comment by ckrez** [comment]
Dunno for sure if related but saw this in v3 when hunter generated indicators reached a confidence level of 0.0:

https://github.com/csirtgadgets/csirtg-indicator-py/pull/124/commits/d44f6d4d2676bc1304a656f4c6aa4d2d5bb6c85f

**Comment by wesyoung** [comment]
ahhh good call!
