### ISSUE TITLE
GeoIP.conf settings incorrect in latest build? 

### ISSUE THREAD

**Issue by dmille6** [csirtgadgets/verbose-robot#87]
command run:
docker run -e CIF_TOKEN="${CIF_TOKEN}" -it -p 5000:5000 --name verbose-robot 
Results:
csirtgadgets/verbose-robot
updating geoip
geoipupdate 2.3.1
Opened License file /etc/GeoIP.conf
UserId 999999
LicenseKey 000000000000
Insert product_id GeoLite2-Country
Insert product_id GeoLite2-City
Insert product_id GeoLite2-ASN
Read in license key /etc/GeoIP.conf
Number of product ids 3
url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-Country
md5hex_digest: 00000000000000000000000000000000
url: https://updates.maxmind.com/app/update_getipaddr
Client IP address: 45.19.188.41
md5hex_digest2: f57f24246c849eda2ec017bdf7dfec6f
url: https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=f57f24246c849eda2ec017bdf7dfec6f&user_id=999999&edition_id=GeoLite2-Country
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=f57f24246c849eda2ec017bdf7dfec6f&user_id=999999&edition_id=GeoLite2-Country

**Comment by wesyoung** [comment]
i just ran into this too with another project:

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

effectively you now have to sign up for a maxmind account and supplement your own GeoIP.conf information to make this work.. the only work-around might be in building out your own docker configuration for the moment (having it copy over your personal GeoIP.conf file).

happy to accept a PR if you have other ideas ?

**Comment by wesyoung** [comment]
i think i solved this in 4.0.1 .. requires you to create a maxmind account (documented this in the wiki), export some MAXMIND_ vars before you begin. should "fail open" (eg: run, but no geoip data) if you don't..

**Comment by dmille6** [comment]
thank you so much for handling this

**Comment by dmille6** [comment]
Sorry to be a pest, but it still seems to be a problem, i've registered with maxmind. 
but it seems to cut off my license key when submitting it to docker
**Docker Command:** (i've changed my user ID and Key)
`docker run   -e CIF_TOKEN="${CIF_TOKEN}"   -e MAXMIND_USER_ID="151934"   -e MAXMIND_LICENSE_KEY="3Pil8D9psWd011aj"   -it -p 5000:5000 --name verbose-robot 

**output:**
csirtgadgets/verbose-robot:latest`
geoipupdate 2.3.1
Opened License file /etc/GeoIP.conf
UserId 151948
LicenseKey 3Pil8D9psWd0
Insert product_id GeoLite2-ASN
Insert product_id GeoLite2-City
Insert product_id GeoLite2-Country
Read in license key /etc/GeoIP.conf
Number of product ids 3
url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-ASN
md5hex_digest: 00000000000000000000000000000000
url: https://updates.maxmind.com/app/update_getipaddr
Client IP address: 45.19.188.41
md5hex_digest2: 65e2863eb5339fcfa4b0f34329fec30d
url: https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=65e2863eb5339fcfa4b0f34329fec30d&user_id=151948&edition_id=GeoLite2-ASN
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=65e2863eb5339fcfa4b0f34329fec30d&user_id=151948&edition_id=GeoLite2-ASN

its missing the last 4 characters of my license key in the docker output.. and exits. it cuts off the last 4 charactes using varables or if you hardcode your id and key in.
