### ISSUE TITLE
GeoIP still not working, docker container exits

### ISSUE THREAD

**Issue by dmille6** [csirtgadgets/verbose-robot#89]
Sorry to be a pest, but it still seems to be a problem, i've registered with maxmind.
but it seems to cut off my license key when submitting it to docker
Docker Command: (i've changed my user ID and Key)
`docker run -e CIF_TOKEN="${CIF_TOKEN}" -e MAXMIND_USER_ID="151934" -e MAXMIND_LICENSE_KEY="3Pil8D9psWd011aj" -it -p 5000:5000 --name verbose-robot

output:
csirtgadgets/verbose-robot:latest`
geoipupdate 2.3.1
Opened License file /etc/GeoIP.conf
UserId 151934
LicenseKey 3Pil8D9psWd0
Insert product_id GeoLite2-ASN
Insert product_id GeoLite2-City
Insert product_id GeoLite2-Country
Read in license key /etc/GeoIP.conf
Number of product ids 3
url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-ASN
md5hex_digest: 00000000000000000000000000000000
url: https://updates.maxmind.com/app/update_getipaddr
Client IP address: 45.19.188.41
md5hex_digest2: 65e2863eb5339fcfa4b0f34329fec30d
url: https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=65e2863eb5339fcfa4b0f34329fec30d&user_id=151948&edition_id=GeoLite2-ASN
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=65e2863eb5339fcfa4b0f34329fec30d&user_id=151948&edition_id=GeoLite2-ASN

its missing the last 4 characters of my license key in the docker output.. and exits. it cuts off the last 4 charactes using varables or if you hardcode your id and key in.

**Comment by dmille6** [comment]
i got it.. 
Maxmind has two options for generating keys:
hashed or unhashed.. you need to select "unhashed" key for it to be accepted

**Comment by wesyoung** [comment]
Ah yea. I think it’s because the container is using 2.5 or something. Good catch- will update the doc.
