### ISSUE TITLE
cifsdk-py-v4 : AttributeError: 'HTTP' object has no attribute 'submit'

### ISSUE THREAD

**Issue by dmille6** [csirtgadgets/verbose-robot#91]
i'm copying and pasting the code straight from the cifv4 book:

import logging
from cifsdk.client.http import HTTP as Client

data = '{"indicator":"example4.com","tlp":"amber","confidence":"4","tags":"malware","provider":"example.com","group":"everyone"}'

cli = Client(token='1234',
            remote='https://localhost',
            verify_ssl=False)

ret = cli.submit(data)
print("submission id: {0}".format(ret))

and i get: 
    ret = cli.submit(data)
AttributeError: 'HTTP' object has no attribute 'submit'

the cli.ping DOES work.. so i know my token is correct.. and it is communicating..

**Comment by wesyoung** [comment]
try this:

https://github.com/csirtgadgets/cifsdk-py-v4/wiki#create

i updated the doc a bit- tested, should work.
