### ISSUE TITLE
Unable to create indicators via Swagger 

### ISSUE THREAD

**Issue by neil-unomaha** [csirtgadgets/verbose-robot#94]
Created a local instance of CIF version 4.  It does not appear that one can create a new indicator via the swagger interface.  The indicator POST request via swagger does not provide inputs for various parameters (indicator, tags, itype, etc). The only available parameter is nowait. Screenshot attached. 

![indicators_post_via_swagger](https://user-images.githubusercontent.com/38234505/80821354-27614080-8b9e-11ea-8603-39482254dbee.PNG)

**Comment by wesyoung** [comment]
You might want to try v5- putting more effort into the doc there.. (swagger too)
